nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.6.1.cjs

# This is required for yarn --immutable-cache to work on CI (since it uses a different OS/CPU/libc)
supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64
  libc:
    - current
    - glibc
